busybox:
  enabled: true
  image: busybox
  command: ["sleep", "3600"]

redis:
  replicaCount: 1
  image:
    repository: redis
    tag: "7"
    pullPolicy: IfNotPresent
  resources:
    requests: { cpu: "50m", memory: "64Mi" }
    limits:   { cpu: "200m", memory: "256Mi" }
  service:
    type: ClusterIP
    port: 6379
    targetPort: 6379
  readinessProbe:
    initialDelaySeconds: 5
    timeoutSeconds: 2
    periodSeconds: 10
    failureThreshold: 3
  livenessProbe:
    initialDelaySeconds: 10
    timeoutSeconds: 2
    periodSeconds: 20
    failureThreshold: 3
  persistence:
    enabled: true
    existingClaim: ""          # set to use an existing PVC
    accessMode: ReadWriteOnce
    size: 1Gi
    storageClassName: ""       # default storage class
    mountPath: /data

frontend:
  replicaCount: 1
  image:
    repository: timursamanchi/quote-frontend
    tag: helm
    pullPolicy: IfNotPresent
  containerPort: 80
  service:
    type: ClusterIP
    port: 80
    targetPort: 80
  resources:
    requests: { cpu: "100m", memory: "128Mi" }
    limits:   { cpu: "500m", memory: "512Mi" }
  readinessProbe:
    path: /
    port: 80
    initialDelaySeconds: 5
    timeoutSeconds: 2
    periodSeconds: 10
    failureThreshold: 3
  livenessProbe:
    path: /
    port: 80
    initialDelaySeconds: 10
    timeoutSeconds: 2
    periodSeconds: 20
    failureThreshold: 3
  hpa:
    enabled: true
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 50

backend:
  replicaCount: 1
  image:
    repository: timursamanchi/quote-backend
    tag: helm
    pullPolicy: IfNotPresent
  containerPort: 8080
  service:
    type: ClusterIP
    port: 8080
    targetPort: 8080
  resources:
    requests: { cpu: "100m", memory: "128Mi" }
    limits:   { cpu: "500m", memory: "512Mi" }
  readinessProbe:
    path: /quote
    port: 8080
    initialDelaySeconds: 5
    timeoutSeconds: 2
    periodSeconds: 10
    failureThreshold: 3
  livenessProbe:
    path: /quote
    port: 8080
    initialDelaySeconds: 10
    timeoutSeconds: 2
    periodSeconds: 20
    failureThreshold: 3
  hpa:
    enabled: true
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 50

ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: ""
      paths:
        - path: /
          pathType: Prefix
        - path: /quote
          pathType: Prefix
  tls: []

loadgen:
  enabled: false
  replicaCount: 1
  image:
    repository: busybox
    tag: "1.36"
    pullPolicy: IfNotPresent
  command: ["/bin/sh", "-c"]
  args:
    - |
      while true; do
        wget -qO- "$TARGET_URL" >/dev/null
        sleep ${SLEEP_SECS:-0.05}
      done
  path: /quote
  sleepSeconds: 0.05
  resources:
    requests:
      cpu: 10m
      memory: 16Mi
    limits:
      cpu: 50m
      memory: 32Mi
