###############################################
#
# templates/backend-deployment
#
###############################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "quote-app.fullname" . }}-backend
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "quote-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      {{- include "quote-app.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: backend
  template:
    metadata:
      labels:
        {{- include "quote-app.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: backend
    spec:
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.backend.containerPort }}
          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}
          readinessProbe:
            httpGet:
              path: {{ .Values.backend.readinessProbe.path }}
              port: {{ .Values.backend.readinessProbe.port }}
            initialDelaySeconds: {{ .Values.backend.readinessProbe.initialDelaySeconds }}
            timeoutSeconds: {{ .Values.backend.readinessProbe.timeoutSeconds }}
            periodSeconds: {{ .Values.backend.readinessProbe.periodSeconds }}
            failureThreshold: {{ .Values.backend.readinessProbe.failureThreshold }}
          livenessProbe:
            httpGet:
              path: {{ .Values.backend.livenessProbe.path }}
              port: {{ .Values.backend.livenessProbe.port }}
            initialDelaySeconds: {{ .Values.backend.livenessProbe.initialDelaySeconds }}
            timeoutSeconds: {{ .Values.backend.livenessProbe.timeoutSeconds }}
            periodSeconds: {{ .Values.backend.livenessProbe.periodSeconds }}
            failureThreshold: {{ .Values.backend.livenessProbe.failureThreshold }}

###############################################
#
# templates/backend-service
#
###############################################
apiVersion: v1
kind: Service
metadata:
  name: {{ include "quote-app.fullname" . }}-backend
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "quote-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: {{ .Values.backend.service.type }}
  selector:
    {{- include "quote-app.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend
  ports:
    - protocol: TCP
      port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.targetPort }}

###############################################
#
# templates/frontend-hpa
#
###############################################
{{- if .Values.backend.hpa.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "quote-app.fullname" . }}-backend-hpa
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "quote-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "quote-app.fullname" . }}-backend
  minReplicas: {{ .Values.backend.hpa.minReplicas }}
  maxReplicas: {{ .Values.backend.hpa.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.backend.hpa.targetCPUUtilizationPercentage }}
{{- end }}
