source "https://rubygems.org"

gem "jekyll", "~> 4.3.2"
gem "jekyll-theme-cayman"
gem "jekyll-sass-converter", "~> 2.2.0"  # ⛔ version BEFORE they started requiring sass-embedded

# ⛔ Avoid native binary that breaks on arm64 (sass-embedded uses x86 ELF)

