# 09-backend-hpa.yaml
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: quote-backend-hpa
  namespace: quote-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: quote-backend
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50